### ISSUE TITLE
Bug: Annotation tooltip

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#489] opened 2021-05-16 23:02 UTC
Hovering over the annotated fragment produces this tooltip:

![image](https://user-images.githubusercontent.com/16408198/118415516-53147300-b69a-11eb-98af-5099421eb29f.png)

The final period after 'frequencies' was also highlighted in the pale yellow colour of the first coding for no apparent reason. I switched to another file and back, and the highlight was gone.

**Comment by ccbogel** [comment] 2021-05-17 01:16
The final period after 'frequencies' was also highlighted in the pale yellow colour of the first coding for no apparent reason. I switched to another file and back, and the highlight was gone. Yes I cant easily fix that. its a quirk.

Yes multiple annotations - I had a bug, that instead of updating annotations, kept inserting new ones. This wont happen now as I have fixed the coding error, but existing double ups may need to be deleted.

**Comment by glocalglocal** [comment] 2021-05-17 10:47
> Yes I cant easily fix that. its a quirk.

For the record, I captured the odd highlight here: 

![image](https://user-images.githubusercontent.com/16408198/118476443-08781280-b6fd-11eb-856f-e52961ba43f3.png)

> but existing double ups may need to be deleted.

The problem is I can't delete the annotation. I get the 'Edit Annotation' option in the menu, but nothing happens when I click on it. 

> I can hide the multiple display in the tooltip, if you like.

No need for that if the root cause is dealt with.

**Comment by ccbogel** [comment] 2021-05-17 12:07
The problem is I can't delete the annotation. I get the 'Edit Annotation' option in the menu, but nothing happens when I click on it.
One way is to open the annotation, then delete all the text and then close it.

**Comment by glocalglocal** [comment] 2021-05-17 12:14
> One way is to open the annotation, then delete all the text and then close it.

That was the plan but 'Edit Annotation' did nothing and I couldn't open the annotation. I tried at least 10 times and I couldn't open it. The click closed the menu as expected and then nothing happened. I tried again now and it worked. Weird!

**Comment by ccbogel** [comment] 2021-05-17 22:16
It might be to do with the update  I did.
Hopefully you done have any other 'doubled up annotations'
I will close this for now. but make a new issue if it occurs again.

**Closed by ccbogel** 2021-05-17 22:16 UTC
