### ISSUE TITLE
Changing coders name is broken (+ improvements)

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#310] opened 2020-11-21 17:12 UTC
**Describe the bug**
Changing coders name doesn't work

**To Reproduce**
Go to settings-this coder name and change it. Press ok. If you go to settings again the name is still to default. I tried to close and reopen QualCoder but it didn't work.

Also going to the menu below you see the first line is blanket (no idea why, what's the reason and whether it is intended or not), if you open it 'default' will appear under it.

Is it something which doesn't work only in my system or?

I think it would be great having a + button to add coders and through the pull down menu have the ability to remove them.

This would be very useful as I am going to have a project where I won't be the only coder.

ps: for the aforementioned project, me and my colleague where thinking of working asynchronously (since QualCoder doesn't let two users work on the same project at the same time remotely) on one project. Any suggestions on how we could do that?

Would it be possible sharing 1 qualcoder project between two coders (share the file via internet and open them) or one coder should just code the material send it to the other and let the other do the reports,comparison etc.?

Lubuntu 18.04 QualCoder 2.1 (it says 2.0 but it should be 2.1 I remember there was an issue displaying the wrong version number).

**Comment by ccbogel** [comment] 2020-11-21 20:15
The coder name. Yes if you change the name and then exit (do no codings and no file imports etc). The coder name will not be stored. 
The way qualcoder was setup, I did not separately store a list of coders. Instead, it searches through all the tables (of sources, codes, and codings) for the coder names.
However I will make a  change to fill the coder name box from the config file which should resolve this problem.

You cannot remove coders, for the same above reason. In that the names are drawn from the codings, sources etc tables where coder name X added a file, or a code, or a coded section of text.

In the drop down box. Yes there is a blank option in the coder names. It is intended. When a name is selected/visible, it will then become the coder. So I needed a blank option.

Two people working on the project. Yes share it, zip the folder and email it so that you can each work on it. But make sure you email back any work done. Or let one person do all the coding first, then zip and email it to the other person to do their coding.

Yes the 2.0 / 2.1 issue will remain, until I put up a new release (correctly) for 2.2.

**Comment by ccbogel** [comment] 2020-11-29 22:27
I would like to close this issue soon. let me know if the issue is ongoing

**Comment by ccbogel** [comment] 2020-12-07 20:55
I think sorted now? will close.

**Closed by ccbogel** 2020-12-07 20:55 UTC
