### ISSUE TITLE
RQDA import loses colours in codes and highlights in coded text

### ISSUE THREAD

**Issue by glocalglocal** [ccbogel/QualCoder#85] opened 2020-07-07 12:27 UTC
Importing RQDA files sort of works but the codes list in 'Code Text' displays as dark fonts on dark background -- practically unreadable. There were around 30 codes in the RQDA file using all sorts of codes. I changed the colours in QualCoder but the text on the right still looks as uncoded / un-highlighted. It is coded though because when I ask QualCoder to produce a codes report it works. 

I will try to follow up with the RQDA file after I remove data I am not allowed to share. Not necessarily easy because my Windows RQDA installation doesn't work any more but I hope I can manage. 

(Windows 10 x64, QualCoder 1.9, Python 3.8 32 bit)

**Comment by ccbogel** [comment] 2020-07-07 12:43
Hi, actually I think I might know what some of the problem is - in that the text remains uncoded on the right.
The coder name is very important in being able to see the codes. I bet that the default coder name that is in QualCoder is different. What coder name was used in RQDA? - You can find out by opening the sql dialog and running this:
SELECT owner FROM  code_text 

If this works - change the default coder name to the one showing in the above sql statement.
Secondly, if it works, I will have to add a warning so that end users do not get confused by this issue in the future.

**Comment by glocalglocal** [comment] 2020-07-07 13:41
You were right. The original coder name was different. Highlights restored now -- thanks. Can't the app alert the user and offer a list of known coders in the coding dialogue and wherever it's relevant?

I think I found out why codes are blackened (see screenshot). The SQL export shows no colour info for the imported file -- only the code names (edit CSV attached). In fact, one out of 30+ codes has a colour associated. When I change the colours from within QualCoder and export the SQL data again, there are colour assignments as normal. 

![codes](https://user-images.githubusercontent.com/16408198/86789763-30b3d100-c057-11ea-9b68-1b1f130b3de0.jpg)

[codes.txt](https://github.com/ccbogel/QualCoder/files/4885169/codes.txt)

**Comment by ccbogel** [comment] 2020-07-07 21:57
Thanks - this helps heaps. OK I have improved the RQDA import so now:
Random qualcoder colours as assigned to the rqda codes - rather than the blanks that have occurred so far.
The default coder name is obtained from RQDA - so there will be no confusion over the coded text not showing.
I have also NOT imported RQDA coded text were the selected text is blank. This might help to reduce the 'None type errors' that are occurring.
Please let me know if the import is much improved. Note I manufactured an RQDA database for testing so it is not original like yours.

**Closed** 2020-07-08 04:06 UTC
