### ISSUE TITLE
Rearranging Codes and Categories

### ISSUE THREAD

**Issue by mirren** [ccbogel/QualCoder#274] opened 2020-10-19 12:55 UTC
**Describe the bug**
When rearranging codes and categories in the coding window by dragging the following error appears occasionally. Subsequently it is not possible to reopen the coding (or reports) window, if this is closed. If project is closed and opened up again, operation continues as normal. 

QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 0 ) in model QTreeModel(0x7f9567542aa0)
QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 3 ) in model QTreeModel(0x7f9567542aa0)
QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 0 ) in model QTreeModel(0x7f9567542aa0)
QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 3 ) in model QTreeModel(0x7f9567542aa0)
Traceback (most recent call last):
  File "... /QualCoder/qualcoder/reports.py", line 1800, in search
    cur.execute(sql, parameters)

ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.

**To Reproduce**
Not exactly clear what are the exact conditions to reproduce this error; it does not appear every time but it is not infrequent if one works with updating the coding system. Had to restart two or three times within 2 hours 

**Expected behavior**
Rearranging codes and categories should not have produced this error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OSX 10.15.6 Catalina, Python 3.8  

**Additional context**

**Comment by ccbogel** [comment] 2020-10-19 21:01
@mirren In the above error post. I see that you described this occurring in the reports window - as reports.py is listed in the output.
I have disabled drag-enabled items - a oversight on my part - hope this fixes the issue. I have also added a try catch to catch any further incorrect bindings.
If further errors occur of this nature, please post the error text and anything relevant in the qualcoder.log file

**Comment by mirren** [comment] 2020-10-20 07:15
I am getting these errors now 

wrapped C/C++ object of type DialogCodeText has been deleted
2020/10/20 09:08:15 ERROR __main__.clean_dialog_refs wrapped C/C++ object of type DialogCodeText has been deleted
wrapped C/C++ object of type DialogCodeText has been deleted
2020/10/20 09:09:45 DEBUG __main__.text_coding wrapped C/C++ object of type DialogCodeText has been deleted
2020/10/20 09:10:02 ERROR reports.exception_handler Uncaught exception: Traceback (most recent call last):
  File "qualcoder/qualcoder.py", line 1140, in closeEvent
    def closeEvent(self, event):

KeyboardInterrupt: 

By the way, the ability to drag and drop codes seems to be lost again (perhaps temporarily) so I cannot reproduce; there must be something strange with Python QT and OSX Catalina

**Comment by mirren** [comment] 2020-10-20 09:03
Here is the log file. I did get bugs also when exporting the project or codebook using REFI-QDA

[QualCoder.log](https://github.com/ccbogel/QualCoder/files/5407631/QualCoder.log)

**Comment by mirren** [comment] 2020-10-20 09:04
Dragging and Dropping is back again by the way. Quite strange

**Comment by ccbogel** [comment] 2020-10-20 10:55
There seems to be some issues with drag and drop on a Mac, see here:

https://www.switchingtomac.com/tutorials/osx/how-to-fix-drag-drop-not-working-on-mac/

**Comment by ccbogel** [comment] 2020-10-20 11:01
The errors with DialogCodeText being deleted is not a very minor issue. I will remove the logging of this so that users don't see it in the log file.
Thanks re the refi export  Iwill try and fix these issues.

**Comment by mirren** [comment] 2020-10-20 11:04
I also get this sometimes when trying to unmark a code 

Traceback (most recent call last):
  File "/Users/georgios/QualCoder/qualcoder/code_text.py", line 496, in textEdit_menu
    self.unmark(cursor.position())

  File "/Users/georgios/QualCoder/qualcoder/code_text.py", line 1443, in unmark
    ui = DialogSelectItems(self.app, unmarked_list, _("Select code to unmark"), "single")

  File "/Users/georgios/QualCoder/qualcoder/select_items.py", line 86, in __init__
    if not d['name']:

KeyError: 'name'

**Comment by ccbogel** [comment] 2020-10-20 11:14
@mirren  Great. thanks - that information gives me enough detail to reproduce the error. Now working on a solution.

**Comment by ccbogel** [comment] 2020-10-20 11:23
@mirren OK that is fixed now. It was an error in the order of operations when marking. It kept two copies of the same marked code, even though it told you you could not do this. Then when unmarking the two identical copies caused a problem.

**Comment by mirren** [comment] 2020-10-20 11:33
Great! There is another little thing; the count on the coding window does not always correspond to the reality. 
There are codes for which you can see associated text but count does not have a value etc. 
Or count may be increasing and the suddenly drops back to a low value. Not sure what is wrong.

**Comment by mirren** [comment] 2020-10-20 11:49
Also I am getting this when merging codes: 

Traceback (most recent call last):
  File "/qualcoder/code_text.py", line 631, in eventFilter
    self.item_moved_update_data(item, parent)

  File "/qualcoder/code_text.py", line 818, in item_moved_update_data
    self.merge_codes(self.codes[found], parent)

  File "/qualcoder/code_text.py", line 850, in merge_codes
    QtWidgets.QInformationDialog(None, _("Cannot merge"), msg)

AttributeError: module 'PyQt5.QtWidgets' has no attribute 'QInformationDialog'

**Comment by ccbogel** [comment] 2020-10-20 12:07
A thats an error that I have fixed now. But it is covering another issue.
I will close this issue now. but each different thing, should be in its own github Issue.

**Closed by ccbogel** 2020-10-20 12:07 UTC
