### ISSUE TITLE
Can't Install 2.8 on Debian

### ISSUE THREAD

**Issue by ventolinmono** [ccbogel/QualCoder#597] opened 2021-12-30 23:28 UTC
Hi

First time trying QualCoder.

I'm on **Debian 10** and i get this error when installing **Qualcoder 2.8**:
`No local packages or working download links found for PyQt5-Qt5>=5.15.2 error: Could not find suitable distribution for Requirement.parse('PyQt5-Qt5>=5.15.2')`

Tried also installing qualcoder-2.4.deb but nothing happens when trying to open it.

It's great that there are libre QDAS! :D Thanks!

**Comment by ccbogel** [comment] 2022-01-05 10:08
@ventolinmono hello, did you begin by doing this line of code from the terminal:

`sudo apt install python3-pip python3-lxml python3-ply python3-six python3-pdfminer python3-chardet python3-pyqt5 python3-pillow`

Also check what python version you have,  I am presuming is is 3.6 or newer. In terminal type:
`python3`
this opens the python interpreter and shows the version at the top. Ctrl+z to exit.

**Comment by ventolinmono** [comment] 2022-01-06 00:23
`python3` gives me **Python 3.7.3**
and that line of code gives no errors.

**Comment by ccbogel** [comment] 2022-01-06 00:57
ok, thats good.

So then the following instructions, to Install additional modules:

`sudo python3 -m pip install pdfminer.six openpyxl ebooklib pydub SpeechRecognition`

The, Building and install QualCoder, from the downloaded folder type

`sudo python3 setup.py install`

    To run type

`qualcoder`

After each step, let me know if each step works.

**Comment by ccbogel** [comment] 2022-01-06 01:00
You can use the latest version too, if you Download the master from the green Code button.
![pic1](https://user-images.githubusercontent.com/5834638/148311259-94087c0e-1589-4309-a644-bd9995ba7421.png)

**Comment by ventolinmono** [comment] 2022-01-06 01:38
First command gives me this:

> WARNING: You are using pip version 20.2.2; however, version 21.3.1 is available. You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

Tried upgrading pip gives me this:

> Defaulting to user installation because normal site-packages is not writeable. Requirement already satisfied.

**Comment by ccbogel** [comment] 2022-01-06 01:50
try: 
`sudo pip install --upgrade pip`

**Comment by ventolinmono** [comment] 2022-01-06 01:57
`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

:/

**Comment by ccbogel** [comment] 2022-01-06 04:46
OK, well don't upgrade pip. It should be ok to use as is.
Or try doing a regular upgrade and update:

`sudo apt update; sudo apt upgrade`

continue installing the extra modules as shown above.

**Comment by ccbogel** [comment] 2022-01-12 22:43
I am really stumped how to fix your problem. 
One possibility might be to use a newer version of python, e.g. 3.9 or 3.10 but I am only guessing here.

Dist and build are normally locked.
![pic1](https://user-images.githubusercontent.com/5834638/149234630-c45cf64e-b8ac-4e4e-8bb9-01c5d904d090.png)

**Comment by ventolinmono** [comment] 2022-01-12 23:26
Don't worry, thanks anyway. I'll try to repair my python and pip installations. I did it with not enough care and probably messed something up.

**Comment by stragu** [comment] 2022-02-04 04:05
I get something similar on Ubuntu 18.04, when following the instructions in the README, running the `setup.py install` command:

```bash
[...]
Processing dependencies for Qualcoder==2.9
Searching for PyQt5-Qt5>=5.15.2
Reading https://pypi.python.org/simple/PyQt5-Qt5/
No local packages or working download links found for PyQt5-Qt5>=5.15.2
error: Could not find suitable distribution for Requirement.parse('PyQt5-Qt5>=5.15.2')
```

**Comment by ccbogel** [comment] 2022-02-04 04:27
@stragu OK two suggestions. 
One suggestion is use a newer version of python. e.g. python3.8 or newer - maybe this is what is needed.

Second suggestion is - try the 2.9 ubuntu binary that I uploaded to the releases - this will have all the python modules inside it, double click to run

**Comment by stragu** [comment] 2022-02-04 13:53
@ccbogel : thank you for the suggestions!

* I have Python 3.9 currently
* about upgrading pyqt5: I just looked around and I think the issue is that I use Anaconda on this computer, and they are stuck with an older pyqt5 version for now. I don't want to break anything, I've had issues in the past [using the two together](https://www.anaconda.com/blog/using-pip-in-a-conda-environment). I might come in a future version of Anaconda though, and will keep you posted :slightly_smiling_face:

**Comment by ccbogel** [comment] 2022-02-04 19:25
Ok. Thank you for that information.

**Comment by stragu** [comment] 2022-02-07 02:20
OK, I just realised that this issue is not limited to just QualCoder. Other QT applications are now failing to start on my computer, including BOINC, Cadence and QGIS, giving me a similar error. For example, when starting QGIS:

```
Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 74, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.6/dist-packages/PyQt5-5.15.6-py3.6-linux-x86_64.egg/PyQt5/QtCore.abi3.so)
```

I am not sure if this issue is unrelated to the install process of QualCoder, or if it was indeed the QualCoder script that messed things up. I will try a reinstall of my Python distribution and will report back!

**Comment by ccbogel** [comment] 2022-02-07 03:07
I hope it is not related to the QC install - but this was for python 3.9.
I noticed the last line of the above error was for python 3.6 - but you have been using python 3.9 for QC?
"required by /usr/local/lib/python3.6/dist-pack"

Perhaps first try downloading QGIS etc and reinstalling them first.

**Comment by stragu** [comment] 2022-02-07 12:13
Good spotting about the different Python version! That put me onto the solution, and I can now use all the applications I couldn't use. It was indeed when I followed the README instructions that things broke, and the culprit was the use of `sudo` when installing modules.

Let me run you through it, just in case it proves useful to you and to others:

First, I reinstalled Anaconda, and that solved my issue with BOINC only. Not sure why that is, but also: I wasn't seeing the same error message when BOINC wouldn't start, so we can ignore that. Even after reinstalling Anaconda, I still couldn't use applications like Cadence, ReText and QGIS because of that PyQt5 issue:

ReText:

```
~$ retext
Traceback (most recent call last):
  File "/usr/bin/retext", line 26, in <module>
    from ReText import datadirs, settings, globalSettings, app_version
  File "/usr/share/retext/ReText/__init__.py", line 24, in <module>
    from PyQt5.QtCore import QByteArray, QLocale, QSettings, QStandardPaths
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.6/dist-packages/PyQt5-5.15.6-py3.6-linux-x86_64.egg/PyQt5/QtCore.abi3.so)
```

Cadence:

```
~$ cadence
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence.py", line 25, in <module>
    from PyQt5.QtCore import QFileSystemWatcher, QThread, QSemaphore
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.6/dist-packages/PyQt5-5.15.6-py3.6-linux-x86_64.egg/PyQt5/QtCore.abi3.so)
```

QGIS:

```
Couldn't load SIP module.
Python support will be disabled.
Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 74, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/local/lib/python3.6/dist-packages/PyQt5-5.15.6-py3.6-linux-x86_64.egg/PyQt5/QtCore.abi3.so)
```

Pretty obvious culprit here. I had a similar issue a while back with QGIS, and ended up in the same Q&As and forums. As recommended on most of them, I tried to uninstall PyQt5 with pip, to then give priority to the system's` python3-pyqt5` package: it did not work.

```
~$ pip3 uninstall PyQt5
WARNING: Skipping PyQt5 as it is not installed.
```

Very weird, because it's right there in the error message!
Looking into the Python 3.6 modules:

```
~$ ls /usr/local/lib/python3.6/dist-packages
dns                               __pycache__
dnspython-1.15.0.dist-info        pydub
easy-install.pth                  pydub-0.25.1.dist-info
ecdsa                             PyQt5-5.15.6-py3.6-linux-x86_64.egg
ecdsa-0.13.dist-info              PyQt5_sip-12.9.1-py3.6-linux-x86_64.egg
electrum                          PySocks-1.6.8.egg-info
Electrum-3.2.2.egg-info           qdarkstyle
electrum_gui                      QDarkStyle-2.5.4.dist-info
electrum_plugins                  qrcode
jsonrpclib                        qrcode-6.0.dist-info
jsonrpclib_pelix-0.3.1.dist-info  Qualcoder-2.9-py3.6.egg
pbkdf2-1.3.egg-info               sip-4.19.8.dist-info
pbkdf2.py                         sip.so
pdfminer                          sockshandler.py
pdfminer.six-20211012.dist-info   socks.py
pyaes                             speech_recognition
pyaes-1.6.1.egg-info              SpeechRecognition-3.8.1.dist-info
```

Looks like this is where the modules QualCoder asked for ended up being installed when following the README.

As you mentioned, there is a Python version mismatch. My default version of Python is 3.9:

```
~$ python3 --version
Python 3.9.7
```

BUT! The python version when being root is..... 3.6!

```
~$ sudo python3 --version
[sudo] password for xxx: 
Python 3.6.9
```

I just learned today that [the user's Python version might be different to root's Python version](https://superuser.com/questions/600349/why-sudo-python-and-python-in-terminal-start-two-different-versions-python)! I had no idea.

So, because the README says to install some modules with `sudo python3 -m pip install`, I then tried:

```
~$ sudo python3 -m pip uninstall PyQt5
The directory '/home/stragu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling PyQt5-5.15.6:
  /usr/local/lib/python3.6/dist-packages/PyQt5-5.15.6-py3.6-linux-x86_64.egg
Proceed (y/n)? y
  Successfully uninstalled PyQt5-5.15.6
```

And voilà, everything works again.

I have seen quite a few times people strongly recommending _not_ installing python module with `sudo`. Maybe that's the issue here? Should the README only use `sudo` for the system packages that absolutely require it (i.e. `apt install`), and not use it for the python modules installed with pip?

**Comment by stragu** [comment] 2022-02-07 12:53
And to follow up: because I am an Anaconda user, I tried the following slightly modified instructions, removing the use of `sudo` for installing python modules:

1. Download the source code archive
2. Extract
3. Install the necessary system packages: `sudo apt install python3-pip python3-lxml python3-ply python3-six python3-pdfminer python3-chardet python3-pyqt5 python3-pillow`
(note that `python3-pillow` gets replaced by `python3-pil`, and `python3-pdfminer` is not found)
4. Install the extra modules: `conda install pdfminer.six openpyxl ebooklib pydub SpeechRecognition`
(note that the only module found is `openpyxl`, and its installation warns of an "inconsistent environment")
5. In the extracted directory, build and install QualCoder: `python3 setup.py install`
6. Run it: `qualcoder`

I was able to run QualCoder, but I assume a few features wouldn't work because of the missing modules. In any case, I can use QualCoder, and my other programs still work!

I'll let you know if I end up trying the same with `pip` on top of Anaconda.

**Comment by stragu** [comment] 2022-02-08 02:26
I agree you should remove `sudo` from the module installs (but keep it with the `apt` command) because otherwise, they might be installed for a Python version different to the user's version.

I did try to open the Manage Files dialog and add a PDF, and it seems to work without crashing:

![image](https://user-images.githubusercontent.com/1747497/152892670-96eee2bf-8b76-4035-aa7e-a3fe3d914bae.png)

I was then able to code the PDF's text. Is pdfminer supposed to make it look different?

**Comment by ccbogel** [comment] 2022-02-08 09:03
No, pdfminer is just used for the text extract from the pdf. It might already be installed in the background. I have to double check my python coding, been a while since i looked at pdf import.

**Comment by ccbogel** [comment] 2022-02-12 00:28
OK Closing issue. As I have updated the install instructions to use a virtual environment

**Closed by ccbogel** 2022-02-12 00:28 UTC
