### ISSUE TITLE
cannot import RQDA data

### ISSUE THREAD

**Issue by FLuser1** [ccbogel/QualCoder#596] opened 2021-12-26 03:01 UTC
When I go "Project" and then "Import", I can see "RQDA Project" as an option, but it is not clickable.  I would appreciate any help.  Thanks for creating and sharing the software!

**Comment by ccbogel** [comment] 2021-12-26 05:17
Yes ok. Close the currently opened project first.
Then the RQDA option will become active.

**Comment by ccbogel** [comment] 2021-12-29 22:33
explanation provided above

**Comment by coloquio** [comment] 2022-08-22 17:49
I had had no problems to import RQDA files, so far. A colleague sent me an RQDA project that I imported and received this message: Beginning import from RQDA
Project memo imported
Data import unsuccessful from /home/vicente/Fondecyt_Inst.Infomales.rqda
UNIQUE constraint failed: source.name
Qualcoder loads the files but it does not loads the codings. I checked the RQDA as a sql database and the codes are indeed in there. BTW, itś no t an issue with the coder, which is well identified. 

Any hints to solve this issue?

**Comment by ccbogel** [comment] 2022-08-22 22:08
Ah, the problem is that there are 2 files with the same name in RQDA that QC is trying to import, then it crashes. (So then codings are not imported). I have not seen this issue before.

**Comment by ccbogel** [comment] 2022-08-22 23:51
I have uploaded a fix for this in the latest code. It will add some random numbers at the end of duplicated text file names. 
Please let me know if this now works for you.

**Comment by coloquio** [comment] 2022-08-23 16:28
Great I'll try and tell you.

**Comment by coloquio** [comment] 2022-08-25 13:10
Thanks for the patch; it solved the issue. In fact, two files had the same name in the project. The situation occurred because one coder worked on files with the same name in different machines and they got in the same project in RQDA; deleting one of them was not an option.

**Comment by ccbogel** [comment] 2022-08-25 22:22
fixed

**Closed by ccbogel** 2022-08-25 22:22 UTC
Labels: current priority
